
use legumeDB;
CREATE TABLE  `LEGUME` (
  `LEGUME_ID` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `NAME` varchar(20) NOT NULL,
  PRIMARY KEY (`LEGUME_ID`) USING BTREE,
  UNIQUE KEY `UNI_NAME` (`NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8;
